# Generated by Django 3.2.14 on 2022-12-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('grades', models.IntegerField()),
                ('pluses', models.IntegerField()),
                ('class_name', models.CharField(max_length=2)),
            ],
        ),
    ]
