# Generated by Django 3.2.14 on 2022-12-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
