# Generated by Django 3.2.14 on 2022-12-05 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_codes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Codes',
            new_name='Code',
        ),
    ]
