# Generated by Django 3.2.14 on 2022-12-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_codes_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='second_name',
        ),
        migrations.AlterField(
            model_name='code',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
